F
======================================================================
FAIL: test_eval_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 26, in test_eval_1
    w.getvalue(), "1:\n3.83\n2.48\n4.72\n")
AssertionError: '1:\n3.83\n2.57\n4.66\n0.33\n' != '1:\n3.83\n2.48\n4.72\n'
  1:
  3.83
+ 2.48
+ 4.72
- 2.57
- 4.66
- 0.33


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
