F
======================================================================
FAIL: test_eval_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 26, in test_eval_1
    w.getvalue(), "10040:\n4.2379999999999995\n")
AssertionError: '' != '10040:\n4.2379999999999995\n'
+ 10040:
+ 4.2379999999999995


----------------------------------------------------------------------
Ran 1 test in 0.517s

FAILED (failures=1)
CURRENT CUSTOMER <class 'str'>
IT WORKS! (2236702, 2003) 4.333
IT WORKS! (2236702, 2005) 4.506
IT WORKS! (2236702, 2002) 3.972
IT WORKS! (2236702, 2004) 4.205
IT WORKS! (2236702, 2001) 4.174
